### PR TITLE
fix(qwik-city): enable matching route and pathname with an optional t…

### LINKED ISSUE #5003: [🐞] with v1.2.8 trailingSlash:true failed to match route without /
### Which component is affected?

Qwik Runtime

### Describe the bug

With v1.2.8 of qwik if we use the [default setting](https://github.com/pleclech/qwik-1.2.8-trailing-slash-issue/blob/4e485cee3e7551ce412834009d6457320940f8ea/vite.config.ts#L8) or set it to ```qwikCity({trailingSlash: true})``` path without ending slash are not resolved and produce a 404

### Reproduction

https://github.com/pleclech/qwik-1.2.8-trailing-slash-issue

### Steps to reproduce

Use the starter template or use [https://github.com/pleclech/qwik-1.2.8-trailing-slash-issue](https://github.com/pleclech/qwik-1.2.8-trailing-slash-issue)
Run `pnpm install`  followed by `pnpm preview`.
Then navigate to [http://localhost:4173/demo/flower](http://localhost:4173/demo/flower) and you'll see a `404 page`
if you add the [ending slash](http://localhost:4173/demo/flower/) no error 

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 459.84 MB / 15.62 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 9.1.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.8 => 1.2.8 
    @builder.io/qwik-city: ^1.2.8 => 1.2.8 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

I am publishing what i think a fix for it.

### PR DESCRIPTION
**Pull request by pleclech**
…railing slash

match both route and pathname without the optional ending slash

fix #5003

# Overview

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

File: packages/qwik-city/runtime/src/route-matcher.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ import type { PathParams } from './types';
 export function matchRoute(route: string, path: string): PathParams | null {
   const params: PathParams = {};
   let routeIdx: number = startIdxSkipSlash(route);
-  const routeLength = route.length;
+  const routeLength = lengthNoTrailingSlash(route);
```
Comment (mhevery) [inline packages/qwik-city/runtime/src/route-matcher.ts:13]: Nice fix! Can we add a test for this please?
