### PR TITLE
fix(link): Prefetch redirects to error pages. Fixes #5474

### LINKED ISSUE #5474: [🐞] Prefetch redirects to error pages.
### Which component is affected?

Qwik City (routing)

### Describe the bug

`<Link prefetch={true} href="/this-page-doesnt-exist" />`

If the route on the href is not found on prefetch (such as when the user hovers over the element), the page is immediately redirected to the 404 page. This shouldn't happen until the user clicks or navigates to the page.

### Reproduction

https://github.com/eglove/examples/blob/main/apps/qwik-example/src/routes/index.tsx

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 5.58 GB / 31.76 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by iamriajul**
# Overview

Fixes: https://github.com/BuilderIO/qwik/issues/5474

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

This PR fixes the bug by adding a flag to the `loadClientData` function, and update `handlePrefetch` in link-component to use the flag to indicate that the call is intended to just prefetch not actual navigation, So in-case the route does occur unexpected error or doesn't exist it shouldn't redirect to the page.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

File: packages/qwik-city/runtime/src/link-component.tsx [hunk 1]
```diff
@@ -48,7 +48,10 @@ export const Link = component$<LinkProps>((props) => {
           prefetchSymbols(url.pathname);
 
           if (elm.hasAttribute('data-prefetch')) {
-            loadClientData(url, elm, { prefetchSymbols: false });
+            loadClientData(url, elm, {
+              prefetchSymbols: false,
```
Comment (iamriajul) [inline packages/qwik-city/runtime/src/link-component.tsx:52]: I'm a little bit confused about `prefetchSymbols` being `false`!

Comment (wmertens) [reply packages/qwik-city/runtime/src/link-component.tsx:52]: Isn't this specifically to fetch the data separately? The symbols are being fetched elsewhere.

**Review by wmertens — APPROVED** [review]
I was a little worried that there might be other places that prefetch data that would need this flag, but it's indeed only in this place. Nice concise solution!

LGTM

File: packages/qwik-city/runtime/src/link-component.tsx (hunk 1 above)
Comment (iamriajul) [reply packages/qwik-city/runtime/src/link-component.tsx:52]: > Isn't this specifically to fetch the data separately?

I don't know really. Currently the prefetch only data. and symbols are prefetched via the `service-worker` maybe.

Comment (wmertens) [reply packages/qwik-city/runtime/src/link-component.tsx:52]: Actually it's done two lines above this call
