### PR TITLE
fix: context treeshaking with slot

### LINKED ISSUE #2087: Context via Slot works on server but not on client resume
### Qwik Version

0.12.1

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

_No response_

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I'm using context and it just works on the server, so it should work everywhere

### Actual Behaviour

This code shows the problem in the playground. When you click the button, it crashes the runtime

```tsx
import {
  component$,
  Slot,
  createContext,
  useContextProvider,
  useContext,
  useStore,
  useSignal,
} from "@builder.io/qwik";

export const Ctx = createContext("symbols");

export const Symbol = component$(({ id }) => {
  console.log("render Symbol", id);
  const s = useContext(Ctx);
  return <p>Symbol {id}, context value: {s.t}</p>
});

export const Provider = component$(() => {
  console.log("render Provider");
  const s = useStore({ t: "yes" });
  useContextProvider(Ctx, s);
  return (
      <Slot />
  );
});
export const Sub = component$(() => <>
      <Symbol id="A" />
</>)

export const App = component$(() => {
  const t=useSignal(0)
  return (
    <Provider>
      <Sub/>
      <Symbol id="B" />
      <button onClick$={()=>t.value++}>Click me</button>
      {!!t.value && <Symbol id="C" />}
    </Provider>
  );
});
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by manucorporat**
fixes #2087

### CODE REVIEW

File: packages/qwik/src/core/render/ssr/render-ssr.ts [hunk 1]
```diff
@@ -915,10 +926,20 @@ export const escapeAttr = (s: string) => {
...
+const listenersNeedId = (listeners: Listener[]) => {
   return listeners.some((l) => l[1].$captureRef$ && l[1].$captureRef$.length > 0);
 };
 
+const addDynamicSlot = (hostCtx: QContext, elCtx: QContext) => {
+  let dynamicSlots = hostCtx.$dynamicSlots$;
+  if (!dynamicSlots) {
+    hostCtx.$dynamicSlots$ = dynamicSlots = [];
+  }
+  if (!dynamicSlots.includes(elCtx)) {
```
Comment (wmertens) [inline packages/qwik/src/core/render/ssr/render-ssr.ts:938]: O(n), is there a case that this can cause performance issues?

Comment (manucorporat) [reply packages/qwik/src/core/render/ssr/render-ssr.ts:938]: N should be small! HashMaps get faster as N get bigger, for small N, array usually performs better. 
Also hashmap better if in-order removing is important.
